### ISSUE TITLE
Agent提交数据方式

### ISSUE THREAD

**Issue by fasionchan** [lokikiller/trainning#10]
发现年前邮件回复中调到的设计问题还没调整：Agent直接提交数据到Kafka是不合适的，Kafka之前最好用一个Web接口隔离一下，这样做有几个好处：①数据有效性检查；②Kafka访问控制到最小范围，而不是所有机器都可以连；③避免ZK压力等等

**Comment by fasionchan** [comment]
这个issue我还没看到有任何改善性调整呀

**Comment by lokikiller** [comment]
@fasionchan 现在不直接提交给kafka了，先通过rpc提交到了一个数据接口了，还没推送到master，可以查看stage4或者5
